### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by andschdk**

### CODE REVIEW

**Review by fabiocaccamo — APPROVED** [review]

**Comment by fabiocaccamo** [comment]
@andschdk thank you for this PR!

**Comment by andschdk** [comment]
Thank you for accepting my PR, and thank you for this nice repo @fabiocaccamo.
One more thing I forgot to mention in the PR description. You'll need to tag a new release, otherwise, SPM will not be able to work.

**Comment by fabiocaccamo** [comment]
@andschdk I pushed `1.3.2` tag, let me know if it is ok.

**Comment by andschdk** [comment]
Works perfectly, thanks 👍

**Pull request merged**
